/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiResultDTO from '../model/ApiResultDTO';
import InlineObject3 from '../model/InlineObject3';
import InlineObject4 from '../model/InlineObject4';
import InlineObject5 from '../model/InlineObject5';

/**
* Requests service.
* @module api/RequestsApi
* @version 1.0.0
*/
export default class RequestsApi {

    /**
    * Constructs a new RequestsApi. 
    * @alias module:api/RequestsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the initiateInboundPhoneSurvey operation.
     * @callback module:api/RequestsApi~initiateInboundPhoneSurveyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiResultDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate inbound phone survey request
     * An inbound phone survey request informs the InMoment platform of your intent to transfer a phone call into a phone survey hosted by the InMoment platform. This request temporarily reserves a phone number that the current call can be transferred to.
     * @param {module:model/InlineObject3} inlineObject3 
     * @param {module:api/RequestsApi~initiateInboundPhoneSurveyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiResultDTO}
     */
    initiateInboundPhoneSurvey(inlineObject3, callback) {
      let postBody = inlineObject3;
      // verify the required parameter 'inlineObject3' is set
      if (inlineObject3 === undefined || inlineObject3 === null) {
        throw new Error("Missing the required parameter 'inlineObject3' when calling initiateInboundPhoneSurvey");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['IdentityUser', 'Legacy'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiResultDTO;
      return this.apiClient.callApi(
        '/survey/init/inbound/phone', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the initiateInboundSurvey operation.
     * @callback module:api/RequestsApi~initiateInboundSurveyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiResultDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate inbound survey request
     * Used for a delayed entry into the system. Send key metrics about each user that may take the survey (phone/web) and then give them a unique key to enter at the beginning of the survey. When they enter their key, details will be appended to the responses they give.
     * @param {module:model/InlineObject4} inlineObject4 
     * @param {module:api/RequestsApi~initiateInboundSurveyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiResultDTO}
     */
    initiateInboundSurvey(inlineObject4, callback) {
      let postBody = inlineObject4;
      // verify the required parameter 'inlineObject4' is set
      if (inlineObject4 === undefined || inlineObject4 === null) {
        throw new Error("Missing the required parameter 'inlineObject4' when calling initiateInboundSurvey");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['IdentityUser', 'Legacy'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiResultDTO;
      return this.apiClient.callApi(
        '/survey/init/inbound', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the initiateOutboundSurvey operation.
     * @callback module:api/RequestsApi~initiateOutboundSurveyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiResultDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Initiate outbound survey request
     * Outbound survey requests allow you to extend an invitation to a customer to participate in a survey hosted by the InMoment survey system. This invitation can be send to the customer via one of the following methods, depending on the configuration of the outbound campaign in the InMoment platform: SMS (Text Message), Email, Phone call.  The request may be rejected if it violates contact limits configured on the campaign.
     * @param {module:model/InlineObject5} inlineObject5 
     * @param {module:api/RequestsApi~initiateOutboundSurveyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiResultDTO}
     */
    initiateOutboundSurvey(inlineObject5, callback) {
      let postBody = inlineObject5;
      // verify the required parameter 'inlineObject5' is set
      if (inlineObject5 === undefined || inlineObject5 === null) {
        throw new Error("Missing the required parameter 'inlineObject5' when calling initiateOutboundSurvey");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['IdentityUser', 'Legacy'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiResultDTO;
      return this.apiClient.callApi(
        '/survey/init/outbound', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
