/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InMomentPublicRestApi);
  }
}(this, function(expect, InMomentPublicRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InMomentPublicRestApi.AlertDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertDTO', function() {
    it('should create an instance of AlertDTO', function() {
      // uncomment below and update the code to test AlertDTO
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be.a(InMomentPublicRestApi.AlertDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property alertId (base name: "alertId")', function() {
      // uncomment below and update the code to test the property alertId
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property triggerType (base name: "triggerType")', function() {
      // uncomment below and update the code to test the property triggerType
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property triggerFieldId (base name: "triggerFieldId")', function() {
      // uncomment below and update the code to test the property triggerFieldId
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

    it('should have the property triggerFieldName (base name: "triggerFieldName")', function() {
      // uncomment below and update the code to test the property triggerFieldName
      //var instane = new InMomentPublicRestApi.AlertDTO();
      //expect(instance).to.be();
    });

  });

}));
