/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InMomentPublicRestApi);
  }
}(this, function(expect, InMomentPublicRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InMomentPublicRestApi.PublicKasePageContent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublicKasePageContent', function() {
    it('should create an instance of PublicKasePageContent', function() {
      // uncomment below and update the code to test PublicKasePageContent
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be.a(InMomentPublicRestApi.PublicKasePageContent);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property expired (base name: "expired")', function() {
      // uncomment below and update the code to test the property expired
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property overdue (base name: "overdue")', function() {
      // uncomment below and update the code to test the property overdue
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property escalated (base name: "escalated")', function() {
      // uncomment below and update the code to test the property escalated
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property responseId (base name: "responseId")', function() {
      // uncomment below and update the code to test the property responseId
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property creationTime (base name: "creationTime")', function() {
      // uncomment below and update the code to test the property creationTime
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedTime (base name: "lastModifiedTime")', function() {
      // uncomment below and update the code to test the property lastModifiedTime
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property closedTime (base name: "closedTime")', function() {
      // uncomment below and update the code to test the property closedTime
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property closedBy (base name: "closedBy")', function() {
      // uncomment below and update the code to test the property closedBy
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property closedSurveyResponse (base name: "closedSurveyResponse")', function() {
      // uncomment below and update the code to test the property closedSurveyResponse
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

    it('should have the property history (base name: "history")', function() {
      // uncomment below and update the code to test the property history
      //var instane = new InMomentPublicRestApi.PublicKasePageContent();
      //expect(instance).to.be();
    });

  });

}));
