/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InMomentPublicRestApi);
  }
}(this, function(expect, InMomentPublicRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InMomentPublicRestApi.ResponseByPromptDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseByPromptDTO', function() {
    it('should create an instance of ResponseByPromptDTO', function() {
      // uncomment below and update the code to test ResponseByPromptDTO
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be.a(InMomentPublicRestApi.ResponseByPromptDTO);
    });

    it('should have the property surveyId (base name: "surveyId")', function() {
      // uncomment below and update the code to test the property surveyId
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyGatewayId (base name: "surveyGatewayId")', function() {
      // uncomment below and update the code to test the property surveyGatewayId
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "externalId")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property unitExternalId (base name: "unitExternalId")', function() {
      // uncomment below and update the code to test the property unitExternalId
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property offerCode (base name: "offerCode")', function() {
      // uncomment below and update the code to test the property offerCode
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property offerId (base name: "offerId")', function() {
      // uncomment below and update the code to test the property offerId
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property beginTime (base name: "beginTime")', function() {
      // uncomment below and update the code to test the property beginTime
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property answers (base name: "answers")', function() {
      // uncomment below and update the code to test the property answers
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property scores (base name: "scores")', function() {
      // uncomment below and update the code to test the property scores
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property responseSource (base name: "responseSource")', function() {
      // uncomment below and update the code to test the property responseSource
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property complete (base name: "complete")', function() {
      // uncomment below and update the code to test the property complete
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

    it('should have the property exclusionReason (base name: "exclusionReason")', function() {
      // uncomment below and update the code to test the property exclusionReason
      //var instane = new InMomentPublicRestApi.ResponseByPromptDTO();
      //expect(instance).to.be();
    });

  });

}));
