/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InMomentPublicRestApi);
  }
}(this, function(expect, InMomentPublicRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InMomentPublicRestApi.ResponseDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResponseDTO', function() {
    it('should create an instance of ResponseDTO', function() {
      // uncomment below and update the code to test ResponseDTO
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be.a(InMomentPublicRestApi.ResponseDTO);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyGatewayId (base name: "surveyGatewayId")', function() {
      // uncomment below and update the code to test the property surveyGatewayId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyGatewayName (base name: "surveyGatewayName")', function() {
      // uncomment below and update the code to test the property surveyGatewayName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyGatewayAlias (base name: "surveyGatewayAlias")', function() {
      // uncomment below and update the code to test the property surveyGatewayAlias
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyGatewayDnis (base name: "surveyGatewayDnis")', function() {
      // uncomment below and update the code to test the property surveyGatewayDnis
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyId (base name: "surveyId")', function() {
      // uncomment below and update the code to test the property surveyId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyName (base name: "surveyName")', function() {
      // uncomment below and update the code to test the property surveyName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property surveyDescription (base name: "surveyDescription")', function() {
      // uncomment below and update the code to test the property surveyDescription
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "externalId")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property externalCallRecordingId (base name: "externalCallRecordingId")', function() {
      // uncomment below and update the code to test the property externalCallRecordingId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property lastModTime (base name: "lastModTime")', function() {
      // uncomment below and update the code to test the property lastModTime
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property beginTime (base name: "beginTime")', function() {
      // uncomment below and update the code to test the property beginTime
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property dateOfService (base name: "dateOfService")', function() {
      // uncomment below and update the code to test the property dateOfService
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property redemptionCode (base name: "redemptionCode")', function() {
      // uncomment below and update the code to test the property redemptionCode
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property employeeCode (base name: "employeeCode")', function() {
      // uncomment below and update the code to test the property employeeCode
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property loyaltyNumber (base name: "loyaltyNumber")', function() {
      // uncomment below and update the code to test the property loyaltyNumber
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property minutes (base name: "minutes")', function() {
      // uncomment below and update the code to test the property minutes
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property complete (base name: "complete")', function() {
      // uncomment below and update the code to test the property complete
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property read (base name: "read")', function() {
      // uncomment below and update the code to test the property read
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property incidentManagementState (base name: "incidentManagementState")', function() {
      // uncomment below and update the code to test the property incidentManagementState
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property ani (base name: "ani")', function() {
      // uncomment below and update the code to test the property ani
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ipAddress")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property cookieUID (base name: "cookieUID")', function() {
      // uncomment below and update the code to test the property cookieUID
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property offerId (base name: "offerId")', function() {
      // uncomment below and update the code to test the property offerId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property offerName (base name: "offerName")', function() {
      // uncomment below and update the code to test the property offerName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property offerCode (base name: "offerCode")', function() {
      // uncomment below and update the code to test the property offerCode
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property unitId (base name: "unitId")', function() {
      // uncomment below and update the code to test the property unitId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property unitExternalId (base name: "unitExternalId")', function() {
      // uncomment below and update the code to test the property unitExternalId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property unitName (base name: "unitName")', function() {
      // uncomment below and update the code to test the property unitName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property organizationId (base name: "organizationId")', function() {
      // uncomment below and update the code to test the property organizationId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property organizationName (base name: "organizationName")', function() {
      // uncomment below and update the code to test the property organizationName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property assignedUserId (base name: "assignedUserId")', function() {
      // uncomment below and update the code to test the property assignedUserId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property assignedUserName (base name: "assignedUserName")', function() {
      // uncomment below and update the code to test the property assignedUserName
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property assignedUserEmail (base name: "assignedUserEmail")', function() {
      // uncomment below and update the code to test the property assignedUserEmail
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property exclusionReason (base name: "exclusionReason")', function() {
      // uncomment below and update the code to test the property exclusionReason
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property answers (base name: "answers")', function() {
      // uncomment below and update the code to test the property answers
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property incidents (base name: "incidents")', function() {
      // uncomment below and update the code to test the property incidents
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property alerts (base name: "alerts")', function() {
      // uncomment below and update the code to test the property alerts
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property scores (base name: "scores")', function() {
      // uncomment below and update the code to test the property scores
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property tagsString (base name: "tagsString")', function() {
      // uncomment below and update the code to test the property tagsString
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property socialReview (base name: "socialReview")', function() {
      // uncomment below and update the code to test the property socialReview
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property contactId (base name: "contactId")', function() {
      // uncomment below and update the code to test the property contactId
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instane = new InMomentPublicRestApi.ResponseDTO();
      //expect(instance).to.be();
    });

  });

}));
