/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InMomentPublicRestApi);
  }
}(this, function(expect, InMomentPublicRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InMomentPublicRestApi.UserAccountDTOOrganizations();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserAccountDTOOrganizations', function() {
    it('should create an instance of UserAccountDTOOrganizations', function() {
      // uncomment below and update the code to test UserAccountDTOOrganizations
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be.a(InMomentPublicRestApi.UserAccountDTOOrganizations);
    });

    it('should have the property orgId (base name: "orgId")', function() {
      // uncomment below and update the code to test the property orgId
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property orgName (base name: "orgName")', function() {
      // uncomment below and update the code to test the property orgName
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property supportName (base name: "supportName")', function() {
      // uncomment below and update the code to test the property supportName
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property supportEmail (base name: "supportEmail")', function() {
      // uncomment below and update the code to test the property supportEmail
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property supportPhone (base name: "supportPhone")', function() {
      // uncomment below and update the code to test the property supportPhone
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property inboxEnabled (base name: "inboxEnabled")', function() {
      // uncomment below and update the code to test the property inboxEnabled
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property transcriptionEnabled (base name: "transcriptionEnabled")', function() {
      // uncomment below and update the code to test the property transcriptionEnabled
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property taggingEnabled (base name: "taggingEnabled")', function() {
      // uncomment below and update the code to test the property taggingEnabled
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property inboxUserFilter (base name: "inboxUserFilter")', function() {
      // uncomment below and update the code to test the property inboxUserFilter
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property inboxTaggingFilter (base name: "inboxTaggingFilter")', function() {
      // uncomment below and update the code to test the property inboxTaggingFilter
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property locationCount (base name: "locationCount")', function() {
      // uncomment below and update the code to test the property locationCount
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

    it('should have the property dashboardGroups (base name: "dashboardGroups")', function() {
      // uncomment below and update the code to test the property dashboardGroups
      //var instane = new InMomentPublicRestApi.UserAccountDTOOrganizations();
      //expect(instance).to.be();
    });

  });

}));
