/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OptionDTO from './OptionDTO';

/**
 * The AnswerDTO model module.
 * @module model/AnswerDTO
 * @version 1.0.0
 */
class AnswerDTO {
    /**
     * Constructs a new <code>AnswerDTO</code>.
     * @alias module:model/AnswerDTO
     */
    constructor() { 
        
        AnswerDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnswerDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnswerDTO} obj Optional instance to populate.
     * @return {module:model/AnswerDTO} The populated <code>AnswerDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnswerDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('fieldId')) {
                obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'Number');
            }
            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
            if (data.hasOwnProperty('fieldText')) {
                obj['fieldText'] = ApiClient.convertToType(data['fieldText'], 'String');
            }
            if (data.hasOwnProperty('fieldLabel')) {
                obj['fieldLabel'] = ApiClient.convertToType(data['fieldLabel'], 'String');
            }
            if (data.hasOwnProperty('fieldType')) {
                obj['fieldType'] = ApiClient.convertToType(data['fieldType'], 'String');
            }
            if (data.hasOwnProperty('literalValue')) {
                obj['literalValue'] = ApiClient.convertToType(data['literalValue'], 'String');
            }
            if (data.hasOwnProperty('option')) {
                obj['option'] = OptionDTO.constructFromObject(data['option']);
            }
            if (data.hasOwnProperty('commentId')) {
                obj['commentId'] = ApiClient.convertToType(data['commentId'], 'Number');
            }
            if (data.hasOwnProperty('commentType')) {
                obj['commentType'] = ApiClient.convertToType(data['commentType'], 'String');
            }
            if (data.hasOwnProperty('commentArchived')) {
                obj['commentArchived'] = ApiClient.convertToType(data['commentArchived'], 'Boolean');
            }
            if (data.hasOwnProperty('optionId')) {
                obj['optionId'] = ApiClient.convertToType(data['optionId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
AnswerDTO.prototype['id'] = undefined;

/**
 * @member {Number} fieldId
 */
AnswerDTO.prototype['fieldId'] = undefined;

/**
 * @member {String} fieldName
 */
AnswerDTO.prototype['fieldName'] = undefined;

/**
 * @member {String} fieldText
 */
AnswerDTO.prototype['fieldText'] = undefined;

/**
 * @member {String} fieldLabel
 */
AnswerDTO.prototype['fieldLabel'] = undefined;

/**
 * @member {String} fieldType
 */
AnswerDTO.prototype['fieldType'] = undefined;

/**
 * @member {String} literalValue
 */
AnswerDTO.prototype['literalValue'] = undefined;

/**
 * @member {module:model/OptionDTO} option
 */
AnswerDTO.prototype['option'] = undefined;

/**
 * @member {Number} commentId
 */
AnswerDTO.prototype['commentId'] = undefined;

/**
 * @member {String} commentType
 */
AnswerDTO.prototype['commentType'] = undefined;

/**
 * @member {Boolean} commentArchived
 */
AnswerDTO.prototype['commentArchived'] = undefined;

/**
 * @member {Number} optionId
 */
AnswerDTO.prototype['optionId'] = undefined;






export default AnswerDTO;

