/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocalizedStringDTO from './LocalizedStringDTO';
import OptionDTO from './OptionDTO';

/**
 * The DataFieldDTO model module.
 * @module model/DataFieldDTO
 * @version 1.0.0
 */
class DataFieldDTO {
    /**
     * Constructs a new <code>DataFieldDTO</code>.
     * @alias module:model/DataFieldDTO
     */
    constructor() { 
        
        DataFieldDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DataFieldDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataFieldDTO} obj Optional instance to populate.
     * @return {module:model/DataFieldDTO} The populated <code>DataFieldDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataFieldDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], [LocalizedStringDTO]);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], [LocalizedStringDTO]);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [OptionDTO]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('organizationObjectId')) {
                obj['organizationObjectId'] = ApiClient.convertToType(data['organizationObjectId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
DataFieldDTO.prototype['id'] = undefined;

/**
 * @member {String} name
 */
DataFieldDTO.prototype['name'] = undefined;

/**
 * @member {String} externalId
 */
DataFieldDTO.prototype['externalId'] = undefined;

/**
 * @member {Array.<module:model/LocalizedStringDTO>} text
 */
DataFieldDTO.prototype['text'] = undefined;

/**
 * @member {Array.<module:model/LocalizedStringDTO>} label
 */
DataFieldDTO.prototype['label'] = undefined;

/**
 * Collection of options associated with the data field if the type of the field is RATING or MULTIPLE_CHOICE
 * @member {Array.<module:model/OptionDTO>} options
 */
DataFieldDTO.prototype['options'] = undefined;

/**
 * @member {String} type
 */
DataFieldDTO.prototype['type'] = undefined;

/**
 * @member {Number} organizationObjectId
 */
DataFieldDTO.prototype['organizationObjectId'] = undefined;






export default DataFieldDTO;

