/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncidentManagementState from './IncidentManagementState';

/**
 * The IncidentDTO model module.
 * @module model/IncidentDTO
 * @version 1.0.0
 */
class IncidentDTO {
    /**
     * Constructs a new <code>IncidentDTO</code>.
     * @alias module:model/IncidentDTO
     * @param userAccountId {Number} 
     * @param comment {String} 
     * @param incidentManagementState {module:model/IncidentManagementState} 
     */
    constructor(userAccountId, comment, incidentManagementState) { 
        
        IncidentDTO.initialize(this, userAccountId, comment, incidentManagementState);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userAccountId, comment, incidentManagementState) { 
        obj['userAccountId'] = userAccountId;
        obj['comment'] = comment;
        obj['incidentManagementState'] = incidentManagementState;
    }

    /**
     * Constructs a <code>IncidentDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IncidentDTO} obj Optional instance to populate.
     * @return {module:model/IncidentDTO} The populated <code>IncidentDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IncidentDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Date');
            }
            if (data.hasOwnProperty('dateTimeUTC')) {
                obj['dateTimeUTC'] = ApiClient.convertToType(data['dateTimeUTC'], 'Date');
            }
            if (data.hasOwnProperty('userAccountId')) {
                obj['userAccountId'] = ApiClient.convertToType(data['userAccountId'], 'Number');
            }
            if (data.hasOwnProperty('userAccountFirstName')) {
                obj['userAccountFirstName'] = ApiClient.convertToType(data['userAccountFirstName'], 'String');
            }
            if (data.hasOwnProperty('userAccountLastName')) {
                obj['userAccountLastName'] = ApiClient.convertToType(data['userAccountLastName'], 'String');
            }
            if (data.hasOwnProperty('userAccountEmail')) {
                obj['userAccountEmail'] = ApiClient.convertToType(data['userAccountEmail'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('incidentManagementState')) {
                obj['incidentManagementState'] = IncidentManagementState.constructFromObject(data['incidentManagementState']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
IncidentDTO.prototype['id'] = undefined;

/**
 * @member {Date} dateTime
 */
IncidentDTO.prototype['dateTime'] = undefined;

/**
 * @member {Date} dateTimeUTC
 */
IncidentDTO.prototype['dateTimeUTC'] = undefined;

/**
 * @member {Number} userAccountId
 */
IncidentDTO.prototype['userAccountId'] = undefined;

/**
 * @member {String} userAccountFirstName
 */
IncidentDTO.prototype['userAccountFirstName'] = undefined;

/**
 * @member {String} userAccountLastName
 */
IncidentDTO.prototype['userAccountLastName'] = undefined;

/**
 * @member {String} userAccountEmail
 */
IncidentDTO.prototype['userAccountEmail'] = undefined;

/**
 * @member {String} comment
 */
IncidentDTO.prototype['comment'] = undefined;

/**
 * @member {module:model/IncidentManagementState} incidentManagementState
 */
IncidentDTO.prototype['incidentManagementState'] = undefined;






export default IncidentDTO;

