/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncidentManagementState from './IncidentManagementState';
import LocalizedStringDTO from './LocalizedStringDTO';

/**
 * The InlineObject2 model module.
 * @module model/InlineObject2
 * @version 1.0.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:model/InlineObject2
     * @param utcTimestamp {Date} 
     * @param userTimestamp {Date} 
     * @param userId {Number} 
     * @param comment {Array.<module:model/LocalizedStringDTO>} 
     * @param incidentState {module:model/IncidentManagementState} 
     */
    constructor(utcTimestamp, userTimestamp, userId, comment, incidentState) { 
        
        InlineObject2.initialize(this, utcTimestamp, userTimestamp, userId, comment, incidentState);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, utcTimestamp, userTimestamp, userId, comment, incidentState) { 
        obj['utcTimestamp'] = utcTimestamp;
        obj['userTimestamp'] = userTimestamp;
        obj['userId'] = userId;
        obj['comment'] = comment;
        obj['incidentState'] = incidentState;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject2} obj Optional instance to populate.
     * @return {module:model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('noteId')) {
                obj['noteId'] = ApiClient.convertToType(data['noteId'], 'String');
            }
            if (data.hasOwnProperty('utcTimestamp')) {
                obj['utcTimestamp'] = ApiClient.convertToType(data['utcTimestamp'], 'Date');
            }
            if (data.hasOwnProperty('userTimestamp')) {
                obj['userTimestamp'] = ApiClient.convertToType(data['userTimestamp'], 'Date');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], [LocalizedStringDTO]);
            }
            if (data.hasOwnProperty('incidentState')) {
                obj['incidentState'] = IncidentManagementState.constructFromObject(data['incidentState']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} noteId
 */
InlineObject2.prototype['noteId'] = undefined;

/**
 * @member {Date} utcTimestamp
 */
InlineObject2.prototype['utcTimestamp'] = undefined;

/**
 * @member {Date} userTimestamp
 */
InlineObject2.prototype['userTimestamp'] = undefined;

/**
 * @member {Number} userId
 */
InlineObject2.prototype['userId'] = undefined;

/**
 * @member {Array.<module:model/LocalizedStringDTO>} comment
 */
InlineObject2.prototype['comment'] = undefined;

/**
 * @member {module:model/IncidentManagementState} incidentState
 */
InlineObject2.prototype['incidentState'] = undefined;






export default InlineObject2;

