/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocalizedStringDTO from './LocalizedStringDTO';

/**
 * The OptionDTO model module.
 * @module model/OptionDTO
 * @version 1.0.0
 */
class OptionDTO {
    /**
     * Constructs a new <code>OptionDTO</code>.
     * @alias module:model/OptionDTO
     */
    constructor() { 
        
        OptionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OptionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OptionDTO} obj Optional instance to populate.
     * @return {module:model/OptionDTO} The populated <code>OptionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OptionDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('localizedLabel')) {
                obj['localizedLabel'] = ApiClient.convertToType(data['localizedLabel'], [LocalizedStringDTO]);
            }
            if (data.hasOwnProperty('ordinalLevel')) {
                obj['ordinalLevel'] = ApiClient.convertToType(data['ordinalLevel'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
OptionDTO.prototype['id'] = undefined;

/**
 * @member {String} name
 */
OptionDTO.prototype['name'] = undefined;

/**
 * @member {String} externalId
 */
OptionDTO.prototype['externalId'] = undefined;

/**
 * @member {String} label
 */
OptionDTO.prototype['label'] = undefined;

/**
 * @member {Array.<module:model/LocalizedStringDTO>} localizedLabel
 */
OptionDTO.prototype['localizedLabel'] = undefined;

/**
 * @member {Number} ordinalLevel
 */
OptionDTO.prototype['ordinalLevel'] = undefined;






export default OptionDTO;

