/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PublicKaseEmployee from './PublicKaseEmployee';
import PublicKasePageClosedSurveyResponse from './PublicKasePageClosedSurveyResponse';
import PublicKasePageHistory from './PublicKasePageHistory';

/**
 * The PublicKasePageContent model module.
 * @module model/PublicKasePageContent
 * @version 1.0.0
 */
class PublicKasePageContent {
    /**
     * Constructs a new <code>PublicKasePageContent</code>.
     * @alias module:model/PublicKasePageContent
     */
    constructor() { 
        
        PublicKasePageContent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicKasePageContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicKasePageContent} obj Optional instance to populate.
     * @return {module:model/PublicKasePageContent} The populated <code>PublicKasePageContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicKasePageContent();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = PublicKaseEmployee.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('expired')) {
                obj['expired'] = ApiClient.convertToType(data['expired'], 'Boolean');
            }
            if (data.hasOwnProperty('overdue')) {
                obj['overdue'] = ApiClient.convertToType(data['overdue'], 'Boolean');
            }
            if (data.hasOwnProperty('escalated')) {
                obj['escalated'] = ApiClient.convertToType(data['escalated'], 'Boolean');
            }
            if (data.hasOwnProperty('responseId')) {
                obj['responseId'] = ApiClient.convertToType(data['responseId'], 'Number');
            }
            if (data.hasOwnProperty('creationTime')) {
                obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Number');
            }
            if (data.hasOwnProperty('lastModifiedTime')) {
                obj['lastModifiedTime'] = ApiClient.convertToType(data['lastModifiedTime'], 'Number');
            }
            if (data.hasOwnProperty('closedTime')) {
                obj['closedTime'] = ApiClient.convertToType(data['closedTime'], 'Number');
            }
            if (data.hasOwnProperty('closedBy')) {
                obj['closedBy'] = PublicKaseEmployee.constructFromObject(data['closedBy']);
            }
            if (data.hasOwnProperty('closedSurveyResponse')) {
                obj['closedSurveyResponse'] = PublicKasePageClosedSurveyResponse.constructFromObject(data['closedSurveyResponse']);
            }
            if (data.hasOwnProperty('history')) {
                obj['history'] = ApiClient.convertToType(data['history'], [PublicKasePageHistory]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PublicKasePageContent.prototype['id'] = undefined;

/**
 * @member {module:model/PublicKaseEmployee} owner
 */
PublicKasePageContent.prototype['owner'] = undefined;

/**
 * @member {String} status
 */
PublicKasePageContent.prototype['status'] = undefined;

/**
 * @member {Boolean} expired
 * @default false
 */
PublicKasePageContent.prototype['expired'] = false;

/**
 * @member {Boolean} overdue
 * @default false
 */
PublicKasePageContent.prototype['overdue'] = false;

/**
 * @member {Boolean} escalated
 * @default false
 */
PublicKasePageContent.prototype['escalated'] = false;

/**
 * @member {Number} responseId
 */
PublicKasePageContent.prototype['responseId'] = undefined;

/**
 * Creation time as a unix timestamp
 * @member {Number} creationTime
 */
PublicKasePageContent.prototype['creationTime'] = undefined;

/**
 * Last modified time as a unix timestamp
 * @member {Number} lastModifiedTime
 */
PublicKasePageContent.prototype['lastModifiedTime'] = undefined;

/**
 * Closed time as a unix timestamp
 * @member {Number} closedTime
 */
PublicKasePageContent.prototype['closedTime'] = undefined;

/**
 * @member {module:model/PublicKaseEmployee} closedBy
 */
PublicKasePageContent.prototype['closedBy'] = undefined;

/**
 * @member {module:model/PublicKasePageClosedSurveyResponse} closedSurveyResponse
 */
PublicKasePageContent.prototype['closedSurveyResponse'] = undefined;

/**
 * @member {Array.<module:model/PublicKasePageHistory>} history
 */
PublicKasePageContent.prototype['history'] = undefined;






export default PublicKasePageContent;

