/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PublicKasePageContent from './PublicKasePageContent';

/**
 * The PublicKasePage model module.
 * @module model/PublicKasePage
 * @version 1.0.0
 */
class PublicKasePage {
    /**
     * Constructs a new <code>PublicKasePage</code>.
     * @alias module:model/PublicKasePage
     */
    constructor() { 
        
        PublicKasePage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicKasePage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicKasePage} obj Optional instance to populate.
     * @return {module:model/PublicKasePage} The populated <code>PublicKasePage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicKasePage();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('numberOfElements')) {
                obj['numberOfElements'] = ApiClient.convertToType(data['numberOfElements'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [PublicKasePageContent]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} number
 */
PublicKasePage.prototype['number'] = undefined;

/**
 * @member {Number} size
 */
PublicKasePage.prototype['size'] = undefined;

/**
 * @member {Number} totalPages
 */
PublicKasePage.prototype['totalPages'] = undefined;

/**
 * @member {Number} numberOfElements
 */
PublicKasePage.prototype['numberOfElements'] = undefined;

/**
 * @member {Number} totalElements
 */
PublicKasePage.prototype['totalElements'] = undefined;

/**
 * @member {Boolean} first
 */
PublicKasePage.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
PublicKasePage.prototype['last'] = undefined;

/**
 * @member {Array.<module:model/PublicKasePageContent>} content
 */
PublicKasePage.prototype['content'] = undefined;






export default PublicKasePage;

