/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseByPromptDTOScoreComponents from './ResponseByPromptDTOScoreComponents';

/**
 * The ResponseDTOScores model module.
 * @module model/ResponseDTOScores
 * @version 1.0.0
 */
class ResponseDTOScores {
    /**
     * Constructs a new <code>ResponseDTOScores</code>.
     * @alias module:model/ResponseDTOScores
     */
    constructor() { 
        
        ResponseDTOScores.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseDTOScores</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseDTOScores} obj Optional instance to populate.
     * @return {module:model/ResponseDTOScores} The populated <code>ResponseDTOScores</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseDTOScores();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('pointsPossible')) {
                obj['pointsPossible'] = ApiClient.convertToType(data['pointsPossible'], 'Number');
            }
            if (data.hasOwnProperty('totalWeight')) {
                obj['totalWeight'] = ApiClient.convertToType(data['totalWeight'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('fieldId')) {
                obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'Number');
            }
            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
            if (data.hasOwnProperty('scoreComponents')) {
                obj['scoreComponents'] = ApiClient.convertToType(data['scoreComponents'], [ResponseByPromptDTOScoreComponents]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ResponseDTOScores.prototype['id'] = undefined;

/**
 * @member {Number} score
 */
ResponseDTOScores.prototype['score'] = undefined;

/**
 * @member {Number} points
 */
ResponseDTOScores.prototype['points'] = undefined;

/**
 * @member {Number} pointsPossible
 */
ResponseDTOScores.prototype['pointsPossible'] = undefined;

/**
 * @member {Number} totalWeight
 */
ResponseDTOScores.prototype['totalWeight'] = undefined;

/**
 * @member {Number} count
 */
ResponseDTOScores.prototype['count'] = undefined;

/**
 * @member {Number} fieldId
 */
ResponseDTOScores.prototype['fieldId'] = undefined;

/**
 * @member {String} fieldName
 */
ResponseDTOScores.prototype['fieldName'] = undefined;

/**
 * @member {Array.<module:model/ResponseByPromptDTOScoreComponents>} scoreComponents
 */
ResponseDTOScores.prototype['scoreComponents'] = undefined;






export default ResponseDTOScores;

