/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlertDTO from './AlertDTO';
import AnswerDTO from './AnswerDTO';
import ContactDTO from './ContactDTO';
import IncidentDTO from './IncidentDTO';
import ResponseDTOScores from './ResponseDTOScores';
import ResponseDTOSocialReview from './ResponseDTOSocialReview';
import TagDTO from './TagDTO';

/**
 * The ResponseDTO model module.
 * @module model/ResponseDTO
 * @version 1.0.0
 */
class ResponseDTO {
    /**
     * Constructs a new <code>ResponseDTO</code>.
     * @alias module:model/ResponseDTO
     */
    constructor() { 
        
        ResponseDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseDTO} obj Optional instance to populate.
     * @return {module:model/ResponseDTO} The populated <code>ResponseDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('surveyGatewayId')) {
                obj['surveyGatewayId'] = ApiClient.convertToType(data['surveyGatewayId'], 'Number');
            }
            if (data.hasOwnProperty('surveyGatewayName')) {
                obj['surveyGatewayName'] = ApiClient.convertToType(data['surveyGatewayName'], 'String');
            }
            if (data.hasOwnProperty('surveyGatewayAlias')) {
                obj['surveyGatewayAlias'] = ApiClient.convertToType(data['surveyGatewayAlias'], 'String');
            }
            if (data.hasOwnProperty('surveyGatewayDnis')) {
                obj['surveyGatewayDnis'] = ApiClient.convertToType(data['surveyGatewayDnis'], 'String');
            }
            if (data.hasOwnProperty('surveyId')) {
                obj['surveyId'] = ApiClient.convertToType(data['surveyId'], 'Number');
            }
            if (data.hasOwnProperty('surveyName')) {
                obj['surveyName'] = ApiClient.convertToType(data['surveyName'], 'String');
            }
            if (data.hasOwnProperty('surveyDescription')) {
                obj['surveyDescription'] = ApiClient.convertToType(data['surveyDescription'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('externalCallRecordingId')) {
                obj['externalCallRecordingId'] = ApiClient.convertToType(data['externalCallRecordingId'], 'String');
            }
            if (data.hasOwnProperty('lastModTime')) {
                obj['lastModTime'] = ApiClient.convertToType(data['lastModTime'], 'Date');
            }
            if (data.hasOwnProperty('beginTime')) {
                obj['beginTime'] = ApiClient.convertToType(data['beginTime'], 'Date');
            }
            if (data.hasOwnProperty('dateOfService')) {
                obj['dateOfService'] = ApiClient.convertToType(data['dateOfService'], 'Date');
            }
            if (data.hasOwnProperty('redemptionCode')) {
                obj['redemptionCode'] = ApiClient.convertToType(data['redemptionCode'], 'String');
            }
            if (data.hasOwnProperty('employeeCode')) {
                obj['employeeCode'] = ApiClient.convertToType(data['employeeCode'], 'String');
            }
            if (data.hasOwnProperty('loyaltyNumber')) {
                obj['loyaltyNumber'] = ApiClient.convertToType(data['loyaltyNumber'], 'String');
            }
            if (data.hasOwnProperty('minutes')) {
                obj['minutes'] = ApiClient.convertToType(data['minutes'], 'Number');
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
            }
            if (data.hasOwnProperty('read')) {
                obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
            }
            if (data.hasOwnProperty('incidentManagementState')) {
                obj['incidentManagementState'] = ApiClient.convertToType(data['incidentManagementState'], 'String');
            }
            if (data.hasOwnProperty('ani')) {
                obj['ani'] = ApiClient.convertToType(data['ani'], 'String');
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
            }
            if (data.hasOwnProperty('cookieUID')) {
                obj['cookieUID'] = ApiClient.convertToType(data['cookieUID'], 'String');
            }
            if (data.hasOwnProperty('offerId')) {
                obj['offerId'] = ApiClient.convertToType(data['offerId'], 'Number');
            }
            if (data.hasOwnProperty('offerName')) {
                obj['offerName'] = ApiClient.convertToType(data['offerName'], 'String');
            }
            if (data.hasOwnProperty('offerCode')) {
                obj['offerCode'] = ApiClient.convertToType(data['offerCode'], 'String');
            }
            if (data.hasOwnProperty('unitId')) {
                obj['unitId'] = ApiClient.convertToType(data['unitId'], 'Number');
            }
            if (data.hasOwnProperty('unitExternalId')) {
                obj['unitExternalId'] = ApiClient.convertToType(data['unitExternalId'], 'String');
            }
            if (data.hasOwnProperty('unitName')) {
                obj['unitName'] = ApiClient.convertToType(data['unitName'], 'String');
            }
            if (data.hasOwnProperty('organizationId')) {
                obj['organizationId'] = ApiClient.convertToType(data['organizationId'], 'Number');
            }
            if (data.hasOwnProperty('organizationName')) {
                obj['organizationName'] = ApiClient.convertToType(data['organizationName'], 'String');
            }
            if (data.hasOwnProperty('assignedUserId')) {
                obj['assignedUserId'] = ApiClient.convertToType(data['assignedUserId'], 'Number');
            }
            if (data.hasOwnProperty('assignedUserName')) {
                obj['assignedUserName'] = ApiClient.convertToType(data['assignedUserName'], 'String');
            }
            if (data.hasOwnProperty('assignedUserEmail')) {
                obj['assignedUserEmail'] = ApiClient.convertToType(data['assignedUserEmail'], 'String');
            }
            if (data.hasOwnProperty('exclusionReason')) {
                obj['exclusionReason'] = ApiClient.convertToType(data['exclusionReason'], 'String');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], [AnswerDTO]);
            }
            if (data.hasOwnProperty('incidents')) {
                obj['incidents'] = ApiClient.convertToType(data['incidents'], [IncidentDTO]);
            }
            if (data.hasOwnProperty('alerts')) {
                obj['alerts'] = ApiClient.convertToType(data['alerts'], [AlertDTO]);
            }
            if (data.hasOwnProperty('scores')) {
                obj['scores'] = ApiClient.convertToType(data['scores'], [ResponseDTOScores]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagDTO]);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('tagsString')) {
                obj['tagsString'] = ApiClient.convertToType(data['tagsString'], 'String');
            }
            if (data.hasOwnProperty('socialReview')) {
                obj['socialReview'] = ResponseDTOSocialReview.constructFromObject(data['socialReview']);
            }
            if (data.hasOwnProperty('contactId')) {
                obj['contactId'] = ApiClient.convertToType(data['contactId'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = ContactDTO.constructFromObject(data['contact']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ResponseDTO.prototype['id'] = undefined;

/**
 * @member {Number} surveyGatewayId
 */
ResponseDTO.prototype['surveyGatewayId'] = undefined;

/**
 * @member {String} surveyGatewayName
 */
ResponseDTO.prototype['surveyGatewayName'] = undefined;

/**
 * @member {String} surveyGatewayAlias
 */
ResponseDTO.prototype['surveyGatewayAlias'] = undefined;

/**
 * @member {String} surveyGatewayDnis
 */
ResponseDTO.prototype['surveyGatewayDnis'] = undefined;

/**
 * @member {Number} surveyId
 */
ResponseDTO.prototype['surveyId'] = undefined;

/**
 * @member {String} surveyName
 */
ResponseDTO.prototype['surveyName'] = undefined;

/**
 * @member {String} surveyDescription
 */
ResponseDTO.prototype['surveyDescription'] = undefined;

/**
 * @member {String} externalId
 */
ResponseDTO.prototype['externalId'] = undefined;

/**
 * @member {String} externalCallRecordingId
 */
ResponseDTO.prototype['externalCallRecordingId'] = undefined;

/**
 * @member {Date} lastModTime
 */
ResponseDTO.prototype['lastModTime'] = undefined;

/**
 * @member {Date} beginTime
 */
ResponseDTO.prototype['beginTime'] = undefined;

/**
 * @member {Date} dateOfService
 */
ResponseDTO.prototype['dateOfService'] = undefined;

/**
 * @member {String} redemptionCode
 */
ResponseDTO.prototype['redemptionCode'] = undefined;

/**
 * @member {String} employeeCode
 */
ResponseDTO.prototype['employeeCode'] = undefined;

/**
 * @member {String} loyaltyNumber
 */
ResponseDTO.prototype['loyaltyNumber'] = undefined;

/**
 * @member {Number} minutes
 */
ResponseDTO.prototype['minutes'] = undefined;

/**
 * @member {Boolean} complete
 * @default false
 */
ResponseDTO.prototype['complete'] = false;

/**
 * @member {Boolean} read
 * @default false
 */
ResponseDTO.prototype['read'] = false;

/**
 * @member {String} incidentManagementState
 */
ResponseDTO.prototype['incidentManagementState'] = undefined;

/**
 * @member {String} ani
 */
ResponseDTO.prototype['ani'] = undefined;

/**
 * @member {String} ipAddress
 */
ResponseDTO.prototype['ipAddress'] = undefined;

/**
 * @member {String} cookieUID
 */
ResponseDTO.prototype['cookieUID'] = undefined;

/**
 * @member {Number} offerId
 */
ResponseDTO.prototype['offerId'] = undefined;

/**
 * @member {String} offerName
 */
ResponseDTO.prototype['offerName'] = undefined;

/**
 * @member {String} offerCode
 */
ResponseDTO.prototype['offerCode'] = undefined;

/**
 * @member {Number} unitId
 */
ResponseDTO.prototype['unitId'] = undefined;

/**
 * @member {String} unitExternalId
 */
ResponseDTO.prototype['unitExternalId'] = undefined;

/**
 * @member {String} unitName
 */
ResponseDTO.prototype['unitName'] = undefined;

/**
 * @member {Number} organizationId
 */
ResponseDTO.prototype['organizationId'] = undefined;

/**
 * @member {String} organizationName
 */
ResponseDTO.prototype['organizationName'] = undefined;

/**
 * @member {Number} assignedUserId
 */
ResponseDTO.prototype['assignedUserId'] = undefined;

/**
 * @member {String} assignedUserName
 */
ResponseDTO.prototype['assignedUserName'] = undefined;

/**
 * @member {String} assignedUserEmail
 */
ResponseDTO.prototype['assignedUserEmail'] = undefined;

/**
 * @member {module:model/ResponseDTO.ExclusionReasonEnum} exclusionReason
 * @default 'NONE'
 */
ResponseDTO.prototype['exclusionReason'] = 'NONE';

/**
 * @member {String} mode
 */
ResponseDTO.prototype['mode'] = undefined;

/**
 * @member {Array.<module:model/AnswerDTO>} answers
 */
ResponseDTO.prototype['answers'] = undefined;

/**
 * @member {Array.<module:model/IncidentDTO>} incidents
 */
ResponseDTO.prototype['incidents'] = undefined;

/**
 * @member {Array.<module:model/AlertDTO>} alerts
 */
ResponseDTO.prototype['alerts'] = undefined;

/**
 * @member {Array.<module:model/ResponseDTOScores>} scores
 */
ResponseDTO.prototype['scores'] = undefined;

/**
 * @member {Array.<module:model/TagDTO>} tags
 */
ResponseDTO.prototype['tags'] = undefined;

/**
 * @member {String} url
 */
ResponseDTO.prototype['url'] = undefined;

/**
 * @member {String} tagsString
 */
ResponseDTO.prototype['tagsString'] = undefined;

/**
 * @member {module:model/ResponseDTOSocialReview} socialReview
 */
ResponseDTO.prototype['socialReview'] = undefined;

/**
 * @member {String} contactId
 */
ResponseDTO.prototype['contactId'] = undefined;

/**
 * @member {module:model/ContactDTO} contact
 */
ResponseDTO.prototype['contact'] = undefined;





/**
 * Allowed values for the <code>exclusionReason</code> property.
 * @enum {String}
 * @readonly
 */
ResponseDTO['ExclusionReasonEnum'] = {

    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE",

    /**
     * value: "BLACKLISTED"
     * @const
     */
    "BLACKLISTED": "BLACKLISTED",

    /**
     * value: "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT": "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "OVERAGE"
     * @const
     */
    "OVERAGE": "OVERAGE",

    /**
     * value: "IP_REPEAT_LIMIT_PER_RESONDENT"
     * @const
     */
    "IP_REPEAT_LIMIT_PER_RESONDENT": "IP_REPEAT_LIMIT_PER_RESONDENT",

    /**
     * value: "OFFENSIVE_LANGUAGE"
     * @const
     */
    "OFFENSIVE_LANGUAGE": "OFFENSIVE_LANGUAGE",

    /**
     * value: "SPEEDER"
     * @const
     */
    "SPEEDER": "SPEEDER",

    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED",

    /**
     * value: "LAG_TIME"
     * @const
     */
    "LAG_TIME": "LAG_TIME",

    /**
     * value: "INVALID_ANSWER"
     * @const
     */
    "INVALID_ANSWER": "INVALID_ANSWER",

    /**
     * value: "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESONDENT"
     * @const
     */
    "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESONDENT": "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESONDENT",

    /**
     * value: "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESONDENT"
     * @const
     */
    "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESONDENT": "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESONDENT",

    /**
     * value: "FRAUD"
     * @const
     */
    "FRAUD": "FRAUD",

    /**
     * value: "PROBABILITY_THROTTLE"
     * @const
     */
    "PROBABILITY_THROTTLE": "PROBABILITY_THROTTLE",

    /**
     * value: "TIME_THROTTLE"
     * @const
     */
    "TIME_THROTTLE": "TIME_THROTTLE",

    /**
     * value: "REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "REPEAT_LIMIT_PER_RESPONDENT": "REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT"
     * @const
     */
    "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT": "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT",

    /**
     * value: "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT"
     * @const
     */
    "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT": "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT",

    /**
     * value: "EXCLUSION_PERIOD"
     * @const
     */
    "EXCLUSION_PERIOD": "EXCLUSION_PERIOD",

    /**
     * value: "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT": "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "CONTACT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "CONTACT_LIMIT_PER_RESPONDENT": "CONTACT_LIMIT_PER_RESPONDENT"
};



export default ResponseDTO;

