/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseByPromptDTOAnswers model module.
 * @module model/ResponseByPromptDTOAnswers
 * @version 1.0.0
 */
class ResponseByPromptDTOAnswers {
    /**
     * Constructs a new <code>ResponseByPromptDTOAnswers</code>.
     * @alias module:model/ResponseByPromptDTOAnswers
     * @param promptId {Number} ID of the prompt for this answer.
     */
    constructor(promptId) { 
        
        ResponseByPromptDTOAnswers.initialize(this, promptId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, promptId) { 
        obj['promptId'] = promptId;
    }

    /**
     * Constructs a <code>ResponseByPromptDTOAnswers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseByPromptDTOAnswers} obj Optional instance to populate.
     * @return {module:model/ResponseByPromptDTOAnswers} The populated <code>ResponseByPromptDTOAnswers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseByPromptDTOAnswers();

            if (data.hasOwnProperty('promptId')) {
                obj['promptId'] = ApiClient.convertToType(data['promptId'], 'Number');
            }
            if (data.hasOwnProperty('answerValue')) {
                obj['answerValue'] = ApiClient.convertToType(data['answerValue'], 'String');
            }
        }
        return obj;
    }


}

/**
 * ID of the prompt for this answer.
 * @member {Number} promptId
 */
ResponseByPromptDTOAnswers.prototype['promptId'] = undefined;

/**
 * The string representation of the answer. For categorical prompts, this should be the DTMF code for the specific answer option.
 * @member {String} answerValue
 */
ResponseByPromptDTOAnswers.prototype['answerValue'] = undefined;






export default ResponseByPromptDTOAnswers;

