/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseDTOSocialReviewRatings from './ResponseDTOSocialReviewRatings';

/**
 * The ResponseDTOSocialReview model module.
 * @module model/ResponseDTOSocialReview
 * @version 1.0.0
 */
class ResponseDTOSocialReview {
    /**
     * Constructs a new <code>ResponseDTOSocialReview</code>.
     * @alias module:model/ResponseDTOSocialReview
     */
    constructor() { 
        
        ResponseDTOSocialReview.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseDTOSocialReview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseDTOSocialReview} obj Optional instance to populate.
     * @return {module:model/ResponseDTOSocialReview} The populated <code>ResponseDTOSocialReview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseDTOSocialReview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('pageId')) {
                obj['pageId'] = ApiClient.convertToType(data['pageId'], 'String');
            }
            if (data.hasOwnProperty('postId')) {
                obj['postId'] = ApiClient.convertToType(data['postId'], 'String');
            }
            if (data.hasOwnProperty('authorId')) {
                obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
            }
            if (data.hasOwnProperty('authorName')) {
                obj['authorName'] = ApiClient.convertToType(data['authorName'], 'String');
            }
            if (data.hasOwnProperty('reviewText')) {
                obj['reviewText'] = ApiClient.convertToType(data['reviewText'], 'String');
            }
            if (data.hasOwnProperty('ratings')) {
                obj['ratings'] = ApiClient.convertToType(data['ratings'], [ResponseDTOSocialReviewRatings]);
            }
            if (data.hasOwnProperty('postDate')) {
                obj['postDate'] = ApiClient.convertToType(data['postDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ResponseDTOSocialReview.prototype['id'] = undefined;

/**
 * @member {module:model/ResponseDTOSocialReview.TypeEnum} type
 * @default 'UNKNOWN'
 */
ResponseDTOSocialReview.prototype['type'] = 'UNKNOWN';

/**
 * @member {String} pageId
 */
ResponseDTOSocialReview.prototype['pageId'] = undefined;

/**
 * @member {String} postId
 */
ResponseDTOSocialReview.prototype['postId'] = undefined;

/**
 * @member {String} authorId
 */
ResponseDTOSocialReview.prototype['authorId'] = undefined;

/**
 * @member {String} authorName
 */
ResponseDTOSocialReview.prototype['authorName'] = undefined;

/**
 * @member {String} reviewText
 */
ResponseDTOSocialReview.prototype['reviewText'] = undefined;

/**
 * @member {Array.<module:model/ResponseDTOSocialReviewRatings>} ratings
 */
ResponseDTOSocialReview.prototype['ratings'] = undefined;

/**
 * @member {Date} postDate
 */
ResponseDTOSocialReview.prototype['postDate'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ResponseDTOSocialReview['TypeEnum'] = {

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN",

    /**
     * value: "FACEBOOK"
     * @const
     */
    "FACEBOOK": "FACEBOOK",

    /**
     * value: "GOOGLE_PLUS"
     * @const
     */
    "GOOGLE_PLUS": "GOOGLE_PLUS",

    /**
     * value: "TRIP_ADVISOR"
     * @const
     */
    "TRIP_ADVISOR": "TRIP_ADVISOR",

    /**
     * value: "TWITTER"
     * @const
     */
    "TWITTER": "TWITTER",

    /**
     * value: "YELP"
     * @const
     */
    "YELP": "YELP",

    /**
     * value: "TRIP"
     * @const
     */
    "TRIP": "TRIP",

    /**
     * value: "EMAIL"
     * @const
     */
    "EMAIL": "EMAIL",

    /**
     * value: "CUSTOM"
     * @const
     */
    "CUSTOM": "CUSTOM"
};



export default ResponseDTOSocialReview;

