/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseByPromptDTOAnswers from './ResponseByPromptDTOAnswers';
import ResponseByPromptDTOScores from './ResponseByPromptDTOScores';

/**
 * The ResponseByPromptDTO model module.
 * @module model/ResponseByPromptDTO
 * @version 1.0.0
 */
class ResponseByPromptDTO {
    /**
     * Constructs a new <code>ResponseByPromptDTO</code>.
     * @alias module:model/ResponseByPromptDTO
     */
    constructor() { 
        
        ResponseByPromptDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseByPromptDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseByPromptDTO} obj Optional instance to populate.
     * @return {module:model/ResponseByPromptDTO} The populated <code>ResponseByPromptDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseByPromptDTO();

            if (data.hasOwnProperty('surveyId')) {
                obj['surveyId'] = ApiClient.convertToType(data['surveyId'], 'Number');
            }
            if (data.hasOwnProperty('surveyGatewayId')) {
                obj['surveyGatewayId'] = ApiClient.convertToType(data['surveyGatewayId'], 'Number');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('unitExternalId')) {
                obj['unitExternalId'] = ApiClient.convertToType(data['unitExternalId'], 'String');
            }
            if (data.hasOwnProperty('offerCode')) {
                obj['offerCode'] = ApiClient.convertToType(data['offerCode'], 'String');
            }
            if (data.hasOwnProperty('offerId')) {
                obj['offerId'] = ApiClient.convertToType(data['offerId'], 'Number');
            }
            if (data.hasOwnProperty('beginTime')) {
                obj['beginTime'] = ApiClient.convertToType(data['beginTime'], 'Date');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'Number');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], [ResponseByPromptDTOAnswers]);
            }
            if (data.hasOwnProperty('scores')) {
                obj['scores'] = ApiClient.convertToType(data['scores'], [ResponseByPromptDTOScores]);
            }
            if (data.hasOwnProperty('responseSource')) {
                obj['responseSource'] = ApiClient.convertToType(data['responseSource'], 'String');
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
            }
            if (data.hasOwnProperty('exclusionReason')) {
                obj['exclusionReason'] = ApiClient.convertToType(data['exclusionReason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique identifier of the survey being responded to.
 * @member {Number} surveyId
 */
ResponseByPromptDTO.prototype['surveyId'] = undefined;

/**
 * The unique identifier of the gateway (endpoint) used to collect the response.
 * @member {Number} surveyGatewayId
 */
ResponseByPromptDTO.prototype['surveyGatewayId'] = undefined;

/**
 * The unique identifier that your system associated with this particular response. Limited to 30 characters.
 * @member {String} externalId
 */
ResponseByPromptDTO.prototype['externalId'] = undefined;

/**
 * The unique identifier your system associates with the unit this response was collected for. This must correspond to a configured unit external ID within the InMoment platform.
 * @member {String} unitExternalId
 */
ResponseByPromptDTO.prototype['unitExternalId'] = undefined;

/**
 * The offer code (or entry code) used by the respondent to gain access to the survey.
 * @member {String} offerCode
 */
ResponseByPromptDTO.prototype['offerCode'] = undefined;

/**
 * The unique identifier of the offer the response was collected in response to.
 * @member {Number} offerId
 */
ResponseByPromptDTO.prototype['offerId'] = undefined;

/**
 * The begin time of the response, in the time zone that the response was collected in.
 * @member {Date} beginTime
 */
ResponseByPromptDTO.prototype['beginTime'] = undefined;

/**
 * @member {Number} mode
 * @default 3
 */
ResponseByPromptDTO.prototype['mode'] = 3;

/**
 * @member {Array.<module:model/ResponseByPromptDTOAnswers>} answers
 */
ResponseByPromptDTO.prototype['answers'] = undefined;

/**
 * @member {Array.<module:model/ResponseByPromptDTOScores>} scores
 */
ResponseByPromptDTO.prototype['scores'] = undefined;

/**
 * The name of the external response source the survey originates from.
 * @member {String} responseSource
 */
ResponseByPromptDTO.prototype['responseSource'] = undefined;

/**
 * Describes this response as containing a complete set of data.
 * @member {Boolean} complete
 * @default true
 */
ResponseByPromptDTO.prototype['complete'] = true;

/**
 * Describes if the data should be excluded for the specified reason.
 * @member {module:model/ResponseByPromptDTO.ExclusionReasonEnum} exclusionReason
 * @default 'NONE'
 */
ResponseByPromptDTO.prototype['exclusionReason'] = 'NONE';





/**
 * Allowed values for the <code>exclusionReason</code> property.
 * @enum {String}
 * @readonly
 */
ResponseByPromptDTO['ExclusionReasonEnum'] = {

    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE",

    /**
     * value: "BLACKLISTED"
     * @const
     */
    "BLACKLISTED": "BLACKLISTED",

    /**
     * value: "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT": "GATEWAY_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "OVERAGE"
     * @const
     */
    "OVERAGE": "OVERAGE",

    /**
     * value: "IP_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "IP_REPEAT_LIMIT_PER_RESPONDENT": "IP_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "OFFENSIVE_LANGUAGE"
     * @const
     */
    "OFFENSIVE_LANGUAGE": "OFFENSIVE_LANGUAGE",

    /**
     * value: "SPEEDER"
     * @const
     */
    "SPEEDER": "SPEEDER",

    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED",

    /**
     * value: "LAG_TIME"
     * @const
     */
    "LAG_TIME": "LAG_TIME",

    /**
     * value: "INVALID_ANSWER"
     * @const
     */
    "INVALID_ANSWER": "INVALID_ANSWER",

    /**
     * value: "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESPONDENT": "DIGITAL_FINGERPRINT_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESPONDENT": "LOYALTY_NUMBER_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "FRAUD"
     * @const
     */
    "FRAUD": "FRAUD",

    /**
     * value: "PROBABILITY_THROTTLE"
     * @const
     */
    "PROBABILITY_THROTTLE": "PROBABILITY_THROTTLE",

    /**
     * value: "TIME_THROTTLE"
     * @const
     */
    "TIME_THROTTLE": "TIME_THROTTLE",

    /**
     * value: "REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "REPEAT_LIMIT_PER_RESPONDENT": "REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT"
     * @const
     */
    "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT": "PERSONAL_IDENTIFYING_INFORMATION_LIMIT_PER_RESPONDENT",

    /**
     * value: "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT"
     * @const
     */
    "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT": "BLANK_TOMBSTONE_LIMIT_PER_RESPONDENT",

    /**
     * value: "EXCLUSION_PERIOD"
     * @const
     */
    "EXCLUSION_PERIOD": "EXCLUSION_PERIOD",

    /**
     * value: "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT": "CERT_CODE_REPEAT_LIMIT_PER_RESPONDENT",

    /**
     * value: "VIDEO_RESPONSE_LIMIT_PER_RESPONDENT"
     * @const
     */
    "VIDEO_RESPONSE_LIMIT_PER_RESPONDENT": "VIDEO_RESPONSE_LIMIT_PER_RESPONDENT",

    /**
     * value: "CONTACT_LIMIT_PER_RESPONDENT"
     * @const
     */
    "CONTACT_LIMIT_PER_RESPONDENT": "CONTACT_LIMIT_PER_RESPONDENT",

    /**
     * value: "REPEAT_LIMIT_PER_REQUEST"
     * @const
     */
    "REPEAT_LIMIT_PER_REQUEST": "REPEAT_LIMIT_PER_REQUEST"
};



export default ResponseByPromptDTO;

