/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseByPromptDTO from './ResponseByPromptDTO';
import ResponseByPromptDTOAnswers from './ResponseByPromptDTOAnswers';
import ResponseByPromptDTOScores from './ResponseByPromptDTOScores';

/**
 * The UpsertParametersDTO model module.
 * @module model/UpsertParametersDTO
 * @version 1.0.0
 */
class UpsertParametersDTO {
    /**
     * Constructs a new <code>UpsertParametersDTO</code>.
     * @alias module:model/UpsertParametersDTO
     * @extends module:model/ResponseByPromptDTO
     * @implements module:model/ResponseByPromptDTO
     */
    constructor() { 
        ResponseByPromptDTO.initialize(this);
        UpsertParametersDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpsertParametersDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpsertParametersDTO} obj Optional instance to populate.
     * @return {module:model/UpsertParametersDTO} The populated <code>UpsertParametersDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpsertParametersDTO();
            ResponseByPromptDTO.constructFromObject(data, obj);
            ResponseByPromptDTO.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement ResponseByPromptDTO interface:
/**
 * The unique identifier of the survey being responded to.
 * @member {Number} surveyId
 */
ResponseByPromptDTO.prototype['surveyId'] = undefined;
/**
 * The unique identifier of the gateway (endpoint) used to collect the response.
 * @member {Number} surveyGatewayId
 */
ResponseByPromptDTO.prototype['surveyGatewayId'] = undefined;
/**
 * The unique identifier that your system associated with this particular response. Limited to 30 characters.
 * @member {String} externalId
 */
ResponseByPromptDTO.prototype['externalId'] = undefined;
/**
 * The unique identifier your system associates with the unit this response was collected for. This must correspond to a configured unit external ID within the InMoment platform.
 * @member {String} unitExternalId
 */
ResponseByPromptDTO.prototype['unitExternalId'] = undefined;
/**
 * The offer code (or entry code) used by the respondent to gain access to the survey.
 * @member {String} offerCode
 */
ResponseByPromptDTO.prototype['offerCode'] = undefined;
/**
 * The unique identifier of the offer the response was collected in response to.
 * @member {Number} offerId
 */
ResponseByPromptDTO.prototype['offerId'] = undefined;
/**
 * The begin time of the response, in the time zone that the response was collected in.
 * @member {Date} beginTime
 */
ResponseByPromptDTO.prototype['beginTime'] = undefined;
/**
 * @member {Number} mode
 * @default 3
 */
ResponseByPromptDTO.prototype['mode'] = 3;
/**
 * @member {Array.<module:model/ResponseByPromptDTOAnswers>} answers
 */
ResponseByPromptDTO.prototype['answers'] = undefined;
/**
 * @member {Array.<module:model/ResponseByPromptDTOScores>} scores
 */
ResponseByPromptDTO.prototype['scores'] = undefined;
/**
 * The name of the external response source the survey originates from.
 * @member {String} responseSource
 */
ResponseByPromptDTO.prototype['responseSource'] = undefined;
/**
 * Describes this response as containing a complete set of data.
 * @member {Boolean} complete
 * @default true
 */
ResponseByPromptDTO.prototype['complete'] = true;
/**
 * Describes if the data should be excluded for the specified reason.
 * @member {module:model/ResponseByPromptDTO.ExclusionReasonEnum} exclusionReason
 * @default 'NONE'
 */
ResponseByPromptDTO.prototype['exclusionReason'] = 'NONE';




export default UpsertParametersDTO;

