/**
 * InMoment Public REST API
 * Welcome to the InMoment Public REST API. Access is restricted to clients of InMoment. Contact your InMoment account manager for more information or visit [https://inmoment.com/](https://inmoment.com/) to learn what InMoment can do for you.   To help you get started, application client libraries for some popular languages and frameworks have been included below. - [csharp-dotnet2](/api/documentation/client/csharp-dotnet2.zip) - [go](/api/documentation/client/go.zip) - [java](/api/documentation/client/java.zip) - [javascript](/api/documentation/client/javascript.zip) - [php](/api/documentation/client/php.zip) - [python](/api/documentation/client/python.zip) - [typescript-angular](/api/documentation/client/typescript-angular.zip) - [typescript-angularjs](/api/documentation/client/typescript-angularjs.zip) - [typescript-jquery](/api/documentation/client/typescript-jquery.zip) - [typescript-node](/api/documentation/client/typescript-node.zip)  Additionally you can use many opensource tools to generate libraries yourself using the [OpenApi 3.0 Spec](/api/documentation/openapi.json)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@inmoment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserAccountDTODashboardGroups from './UserAccountDTODashboardGroups';

/**
 * The UserAccountDTOOrganizations model module.
 * @module model/UserAccountDTOOrganizations
 * @version 1.0.0
 */
class UserAccountDTOOrganizations {
    /**
     * Constructs a new <code>UserAccountDTOOrganizations</code>.
     * @alias module:model/UserAccountDTOOrganizations
     */
    constructor() { 
        
        UserAccountDTOOrganizations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserAccountDTOOrganizations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAccountDTOOrganizations} obj Optional instance to populate.
     * @return {module:model/UserAccountDTOOrganizations} The populated <code>UserAccountDTOOrganizations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAccountDTOOrganizations();

            if (data.hasOwnProperty('orgId')) {
                obj['orgId'] = ApiClient.convertToType(data['orgId'], 'Number');
            }
            if (data.hasOwnProperty('orgName')) {
                obj['orgName'] = ApiClient.convertToType(data['orgName'], 'String');
            }
            if (data.hasOwnProperty('supportName')) {
                obj['supportName'] = ApiClient.convertToType(data['supportName'], 'String');
            }
            if (data.hasOwnProperty('supportEmail')) {
                obj['supportEmail'] = ApiClient.convertToType(data['supportEmail'], 'String');
            }
            if (data.hasOwnProperty('supportPhone')) {
                obj['supportPhone'] = ApiClient.convertToType(data['supportPhone'], 'String');
            }
            if (data.hasOwnProperty('inboxEnabled')) {
                obj['inboxEnabled'] = ApiClient.convertToType(data['inboxEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('transcriptionEnabled')) {
                obj['transcriptionEnabled'] = ApiClient.convertToType(data['transcriptionEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('taggingEnabled')) {
                obj['taggingEnabled'] = ApiClient.convertToType(data['taggingEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('inboxUserFilter')) {
                obj['inboxUserFilter'] = ApiClient.convertToType(data['inboxUserFilter'], 'String');
            }
            if (data.hasOwnProperty('inboxTaggingFilter')) {
                obj['inboxTaggingFilter'] = ApiClient.convertToType(data['inboxTaggingFilter'], 'String');
            }
            if (data.hasOwnProperty('locationCount')) {
                obj['locationCount'] = ApiClient.convertToType(data['locationCount'], 'Number');
            }
            if (data.hasOwnProperty('dashboardGroups')) {
                obj['dashboardGroups'] = ApiClient.convertToType(data['dashboardGroups'], [UserAccountDTODashboardGroups]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} orgId
 */
UserAccountDTOOrganizations.prototype['orgId'] = undefined;

/**
 * @member {String} orgName
 */
UserAccountDTOOrganizations.prototype['orgName'] = undefined;

/**
 * @member {String} supportName
 */
UserAccountDTOOrganizations.prototype['supportName'] = undefined;

/**
 * @member {String} supportEmail
 */
UserAccountDTOOrganizations.prototype['supportEmail'] = undefined;

/**
 * @member {String} supportPhone
 */
UserAccountDTOOrganizations.prototype['supportPhone'] = undefined;

/**
 * @member {Boolean} inboxEnabled
 */
UserAccountDTOOrganizations.prototype['inboxEnabled'] = undefined;

/**
 * @member {Boolean} transcriptionEnabled
 */
UserAccountDTOOrganizations.prototype['transcriptionEnabled'] = undefined;

/**
 * @member {Boolean} taggingEnabled
 */
UserAccountDTOOrganizations.prototype['taggingEnabled'] = undefined;

/**
 * @member {String} inboxUserFilter
 */
UserAccountDTOOrganizations.prototype['inboxUserFilter'] = undefined;

/**
 * @member {String} inboxTaggingFilter
 */
UserAccountDTOOrganizations.prototype['inboxTaggingFilter'] = undefined;

/**
 * @member {Number} locationCount
 */
UserAccountDTOOrganizations.prototype['locationCount'] = undefined;

/**
 * @member {Array.<module:model/UserAccountDTODashboardGroups>} dashboardGroups
 */
UserAccountDTOOrganizations.prototype['dashboardGroups'] = undefined;






export default UserAccountDTOOrganizations;

